### ISSUE TITLE
Help wanted on ECTR event topics

### ISSUE THREAD

**Issue by amikmr1** [dogoodthings/OSGiExamples-ECTREvents-Part8#1]
Hello,

Many thanks for the examples!

Would be helpful to know which place in ECTR all of the ECTR topics are defined. Am referring to....

private static final String OBSERVER_EVENT_OBJECTS_RECEIVED = "plm/observer/notification/event/OBJECTS_RECEIVED";

....the one being handled by you in this example part 8.

**Comment by dogoodthings** [comment]
Hello,
The topics for notification events are defined in com.dscsag.plm.spi.NotificationEventConstants.
The topic "plm/observer/notification/event/OBJECTS_RECEIVED" is not listed there because it has not yet done to any released version.
